URL:
    DATA_URL: "https://archive.ics.uci.edu/ml/machine-learning-databases/00332/OnlineNewsPopularity.zip"
DIR:
    DATA_DIR: "./project/data/raw"
    PKL_DIR: "./project/data/pickle"
    FEATURE_DIR: "./project/feature"
    MODEL_DIR: "./project/models"
    FIGURE_DIR: "./project/figure"
    LOG_DIR: "./project/logs"
PATH:
    DATA_PATH: "./project/data/raw/OnlineNewsPopularity/OnlineNewsPopularity.csv"
    X_TRAIN_PATH: "./project/data/pickle/X_train.pkl"
    Y_TRAIN_PATH: "./project/data/pickle/Y_train.pkl"
    X_TEST_PATH: "./project/data/pickle/X_test.pkl"
    Y_TEST_PATH: "./project/data/pickle/Y_test.pkl"
LGBM:
    LOSS_PATH: "./project/figure/lbg_loss.png"
    IMPORTANCE_PATH: "./project/figure/lgb_importance.png"
    MODEL_PATH: "./project/models/lgb.pkl"
    PARAMS:
        objective: "rmse"
        bagging_freq: 5
        bagging_fraction: 1.0
        boost_from_average: "false"
        boost: "gbdt"
        early_stopping: 1000
        feature_fraction: 1.0
        learning_rate: 0.01
        max_depth: -1
        min_data_in_leaf: 30
        min_sum_hessian_in_leaf: 10.0
        num_leaves: 64
        num_threads: 0
        tree_learner: "serial"
        verbosity: 0